version: '3.0'

scanning-settings:
  max-depth: 6

report:
  dependency-vulnerabilities:
    enabled: true
    auto-ignore-in-report:
      python:
        environment-results: true
        unpinned-requirements: true
      cvss-severity: []
      # vulnerabilities:
      #  48547:
      #    reason: RDFLib vulnerability: https://pyup.io/vulnerabilities/PVE-2022-48547/48547/
      #  44715:
      #    reason: Numpy vulnerability: https://pyup.io/vulnerabilities/CVE-2021-41495/44715/
      #  44716:
      #    reason: Numpy vulnerability: https://pyup.io/vulnerabilities/CVE-2021-41496/44716/
      #  44717:
      #    reason: Numpy vulnerability: https://pyup.io/vulnerabilities/CVE-2021-34141/44717/
      #  70612:
      #    reason: Jinja2 vulnerability. Only used as subdependency for mkdocs++, https://data.safetycli.com/v/70612/97c/
      #  72715:
      #    reason:  update to mkdocs>=9.5.32,  https://data.safetycli.com/v/72715/97c/
