---

# Make DCAT-AP-NO the default standard to use within the physmet domain
default_standard: DCAT-AP-NO

standards:

  default:

    basedOn: https://raw.githubusercontent.com/EMMC-ASBL/tripper/refs/heads/master/tripper/context/0.2/requirements.yaml
