---

standards:

  default:

    basedOn: https://raw.githubusercontent.com/EMMC-ASBL/tripper/refs/heads/master/tripper/context/0.2/requirements.yaml

    "tem:TEMImage":
      required:
        - pixelWidth
        - pixelHeight
