---

standards:

  default:

    basedOn:
      - https://raw.githubusercontent.com/EMMC-ASBL/tripper/refs/heads/master/tripper/context/characterisation/0.1/requirements.yaml
      - https://raw.githubusercontent.com/EMMC-ASBL/tripper/refs/heads/master/tripper/context/imaging/0.1/requirements.yaml

    "tem:TEMImage":
      required:
        - pixelWidth
        - pixelHeight
