name: CI - Update accummulated dependencies PR

on:
  schedule:
    # At 6:30 UTC on the first in the month
    - cron: "30 6 1 * *"
  workflow_dispatch:

jobs:
  create-collected-pr:
    name: External
    uses: SINTEF/ci-cd/.github/workflows/ci_check_pyproject_dependencies.yml@v2.10.0
    if: github.repository_owner == 'EMMC-ASBL'
    with:
      git_username: "TEAM 4.0[bot]"
      git_email: "Team4.0@SINTEF.no"
      target_branch: "ci/dependency-updates"
      install_extras: "[units,mapppings,datadoc,backends,dev,testing-core,pre-commit,dev]"
      pr_labels: "CI/CD,skip_changelog"
    secrets:
      PAT: ${{ secrets.RELEASE_PAT }}
